export interface IHobby {
	name: string;
	emoji: string;
}

export const DEFAULT_HOBBIES: IHobby[] = [
	{ name: "Traveling", emoji: "🌍" },
	{ name: "Reading", emoji: "📖" },
	{ name: "Listening to Music", emoji: "🎧" },
	{ name: "Cooking", emoji: "🍳" },
	{ name: "Video Games", emoji: "🎮" },
	{ name: "Watching Movies", emoji: "🎬" },
	{ name: "Going to the Gym", emoji: "🏋️" },
	{ name: "Eating", emoji: "🍽️" },
	{ name: "Golf", emoji: "⛳" },
	{ name: "Hiking", emoji: "🥾" },
];

export const HOBBIES_BANK: IHobby[] = [
	{ name: "Acting", emoji: "🎭" },
	{ name: "Aerobics", emoji: "🤸" },
	{ name: "Airbrushing", emoji: "🎨" },
	{ name: "Airsoft", emoji: "🔫" },
	{ name: "Astronomy", emoji: "🔭" },
	{ name: "Archery", emoji: "🏹" },
	{ name: "Backpacking", emoji: "🎒" },
	{ name: "Badminton", emoji: "🏸" },
	{ name: "Baking", emoji: "🧁" },
	{ name: "Balloon Modelling", emoji: "🎈" },
	{ name: "Baseball", emoji: "⚾" },
	{ name: "Basketball", emoji: "🏀" },
	{ name: "Belly Dancing", emoji: "🩰" },
	{ name: "Bird Watching", emoji: "🐦" },
	{ name: "Blacksmithing", emoji: "🔨" },
	{ name: "Breadmaking", emoji: "🍞" },
	{ name: "Board Games", emoji: "🎲" },
	{ name: "Boating", emoji: "⛵" },
	{ name: "Bodybuilding", emoji: "💪" },
	{ name: "Botany", emoji: "🌱" },
	{ name: "Bowling", emoji: "🎳" },
	{ name: "Boomerang Throwing", emoji: "🔄" },
	{ name: "Boxing", emoji: "🥊" },
	{ name: "Brewing Beer", emoji: "🍺" },
	{ name: "Bungee Jumping", emoji: "🧗" },
	{ name: "Butterfly Watching", emoji: "🦋" },
	{ name: "Calligraphy", emoji: "🖋️" },
	{ name: "Camping", emoji: "🏕️" },
	{ name: "Candle Making", emoji: "🕯️" },
	{ name: "Canyoning", emoji: "🧗" },
	{ name: "Car Racing", emoji: "🏎️" },
	{ name: "Card Games", emoji: "🃏" },
	{ name: "Cave Diving", emoji: "🕳️" },
	{ name: "Ceramics", emoji: "🏺" },
	{ name: "Chess", emoji: "♟️" },
	{ name: "Cigar Smoking", emoji: "🚬" },
	{ name: "Climbing", emoji: "🧗" },
	{ name: "Coin Collecting", emoji: "💰" },
	{ name: "Cooking", emoji: "🍳" },
	{ name: "Crossword Puzzles", emoji: "✏️" },
	{ name: "Curling", emoji: "🥌" },
	{ name: "Cycling", emoji: "🚴" },
	{ name: "Dancing", emoji: "💃" },
	{ name: "Darts", emoji: "🎯" },
	{ name: "Diving", emoji: "🤿" },
	{ name: "Dog Training", emoji: "🐕" },
	{ name: "Drama", emoji: "🎭" },
	{ name: "Drawing", emoji: "🎨" },
	{ name: "Drone Flying", emoji: "🛸" },
	{ name: "Eating", emoji: "🍽️" },
	{ name: "Embroidery", emoji: "🧵" },
	{ name: "Equestrianism", emoji: "🐎" },
	{ name: "Escape Rooms", emoji: "🔒" },
	{ name: "Fashion", emoji: "👗" },
	{ name: "Falconry", emoji: "🦅" },
	{ name: "Fencing", emoji: "🤺" },
	{ name: "Flower Arranging", emoji: "🌷" },
	{ name: "Fishing", emoji: "🎣" },
	{ name: "Food Tasting", emoji: "🍽️" },
	{ name: "Football", emoji: "⚽" },
	{ name: "Foraging", emoji: "🍄" },
	{ name: "Fossil Hunting", emoji: "🦴" },
	{ name: "Gambling", emoji: "🎰" },
	{ name: "Gardening", emoji: "🌱" },
	{ name: "Genealogy", emoji: "🌳" },
	{ name: "Geocaching", emoji: "🌐" },
	{ name: "Ghost Hunting", emoji: "👻" },
	{ name: "Glassblowing", emoji: "🍷" },
	{ name: "Go Kart Racing", emoji: "🏎️" },
	{ name: "Going to the Gym", emoji: "🏋️" },
	{ name: "Golf", emoji: "⛳" },
	{ name: "Graffiti", emoji: "🎨" },
	{ name: "Guitar Playing", emoji: "🎸" },
	{ name: "Gymnastics", emoji: "🤸" },
	{ name: "Hiking", emoji: "🥾" },
	{ name: "Hockey", emoji: "🏒" },
	{ name: "Ice Skating", emoji: "⛸️" },
	{ name: "Jewelry Making", emoji: "💍" },
	{ name: "Juggling", emoji: "🤹" },
	{ name: "Kayaking", emoji: "🚣" },
	{ name: "Kite Flying", emoji: "🪁" },
	{ name: "Knitting", emoji: "🧶" },
	{ name: "Lacrosse", emoji: "🥍" },
	{ name: "Laser Tag", emoji: "🔫" },
	{ name: "Leather Crafting", emoji: "👞" },
	{ name: "Lego Building", emoji: "🧱" },
	{ name: "Listening to Music", emoji: "🎧" },
	{ name: "Magic Tricks", emoji: "🎩" },
	{ name: "Marathon Running", emoji: "🏃" },
	{ name: "Meditation", emoji: "🧘‍♂️" },
	{ name: "Metal Detecting", emoji: "🔍" },
	{ name: "Mixology", emoji: "🍸" },
	{ name: "Model Building", emoji: "🏠" },
	{ name: "Mountain Climbing", emoji: "⛰️" },
	{ name: "Origami", emoji: "📄" },
	{ name: "Paintball", emoji: "🔵" },
	{ name: "Painting", emoji: "🖌️" },
	{ name: "Photography", emoji: "📸" },
	{ name: "Piano Playing", emoji: "🎹" },
	{ name: "Pottery", emoji: "🏺" },
	{ name: "Puppetry", emoji: "🎎" },
	{ name: "Quilting", emoji: "🛏️" },
	{ name: "Radio Control Cars", emoji: "🚗" },
	{ name: "Rafting", emoji: "🛶" },
	{ name: "Reading", emoji: "📖" },
	{ name: "Rock Climbing", emoji: "🧗" },
	{ name: "Roller Skating", emoji: "🛼" },
	{ name: "Rugby", emoji: "🏉" },
	{ name: "Sailing", emoji: "⛵" },
	{ name: "Sand Sculpting", emoji: "🏖️" },
	{ name: "Scuba Diving", emoji: "🤿" },
	{ name: "Skateboarding", emoji: "🛹" },
	{ name: "Skydiving", emoji: "🪂" },
	{ name: "Snowboarding", emoji: "🏂" },
	{ name: "Soap Making", emoji: "🧼" },
	{ name: "Stand-up Comedy", emoji: "🎤" },
	{ name: "Surfing", emoji: "🏄" },
	{ name: "Swimming", emoji: "🏊" },
	{ name: "Table Tennis", emoji: "🏓" },
	{ name: "Tai Chi", emoji: "🥋" },
	{ name: "Tango Dancing", emoji: "💃" },
	{ name: "Taxidermy", emoji: "🦌" },
	{ name: "Tea Tasting", emoji: "🍵" },
	{ name: "Tennis", emoji: "🎾" },
	{ name: "Theater", emoji: "🎭" },
	{ name: "Traveling", emoji: "🌍" },
	{ name: "Treasure Hunting", emoji: "💎" },
	{ name: "Unicycling", emoji: "🚴‍♂️" },
	{ name: "Urban Exploration", emoji: "🏢" },
	{ name: "Videography", emoji: "📹" },
	{ name: "Video Editing", emoji: "🎥" },
	{ name: "Video Games", emoji: "🎮" },
	{ name: "Volleyball", emoji: "🏐" },
	{ name: "Wakeboarding", emoji: "🏄‍♂️" },
	{ name: "Walking", emoji: "🚶" },
	{ name: "Watching Movies", emoji: "🎬" },
	{ name: "Watercolor Painting", emoji: "🎨" },
	{ name: "Whittling", emoji: "🪒" },
	{ name: "Windsurfing", emoji: "🏄‍♂️" },
	{ name: "Wine Tasting", emoji: "🍷" },
	{ name: "Woodworking", emoji: "🪵" },
	{ name: "Wrestling", emoji: "🤼" },
	{ name: "Writing", emoji: "✍️" },
	{ name: "Yoga", emoji: "🧘" },
	{ name: "Ziplining", emoji: "🌲" },
	{ name: "Zoology", emoji: "🦓" },
];
